### ISSUE TITLE
Log-In Design 

### ISSUE THREAD

**Issue by sumanbudhathoki9808** [sumanbudhathoki9808/E-Challan#10]
- I guess there is no need for "Sign In for what" instead "Sign in" would be fine.
- Design of log-in button 

![Screenshot (33)](https://user-images.githubusercontent.com/59380030/117095447-22713700-ad86-11eb-901d-3e85d469fbf2.png)

**Comment by KabirGc** [comment]
the name has been change to log in and we are working on button

**Comment by sumanbudhathoki9808** [comment]
The button could be made the size of its parent container and the background color should be black. I think this could fix the problem.

**Comment by sumanbudhathoki9808** [comment]
Thank you for solving the bug
