### ISSUE TITLE
pop out log out yes  and no color unmatchable

### ISSUE THREAD

**Issue by KabirGc** [sumanbudhathoki9808/E-Challan#14]

**Comment by biwaskerung999** [comment]
![image](https://user-images.githubusercontent.com/81351933/118248876-81d8f080-b4c4-11eb-9ee2-4ed66d7bc468.png)

**Comment by biwaskerung999** [comment]
![logout](https://user-images.githubusercontent.com/81351933/118248923-8f8e7600-b4c4-11eb-895d-2118bf197024.PNG)

**Comment by biwaskerung999** [comment]
I have fixed this issue. The background of both yes and no gets black when hovered and text gets white now.

**Comment by sumanbudhathoki9808** [comment]
Thank you Biwash
