### ISSUE TITLE
Can go to home page without using username and password through url

### ISSUE THREAD

**Issue by biwaskerung999** [sumanbudhathoki9808/E-Challan#15]
![ravi](https://user-images.githubusercontent.com/81351933/118121776-af189680-b411-11eb-9dd9-9178131d711c.PNG)
![ravi1](https://user-images.githubusercontent.com/81351933/118121787-b0e25a00-b411-11eb-97b3-53bbccd09eba.PNG)

**Comment by KabirGc** [comment]
this a bug that can be fixed using decorators

**Comment by biwaskerung999** [comment]
![Capture](https://user-images.githubusercontent.com/81351933/118205746-c5aa0680-b480-11eb-98e3-b454ddc91f08.PNG)

**Comment by biwaskerung999** [comment]
I have fixed this issue
