### ISSUE TITLE
Github pushing file problem

### ISSUE THREAD

**Issue by biwaskerung999** [sumanbudhathoki9808/E-Challan#16]
![commitissue](https://user-images.githubusercontent.com/81351933/118238885-da09f580-b4b8-11eb-99a4-0f39fdda7a45.PNG)

This problem is shown when I commit the file after adding the file

**Comment by sumanbudhathoki9808** [comment]
We will talk about it in today's meeting.

**Comment by KabirGc** [comment]
try cloning the file in new folder and again try to add, commit, push the file.

**Comment by biwaskerung999** [comment]
I have solved this issue thank you guys for helping.
