### ISSUE TITLE
Cant't log-out from the account while in about-us page and contact-us page

### ISSUE THREAD

**Issue by sumanbudhathoki9808** [sumanbudhathoki9808/E-Challan#17]
While on the about us page and contact us page a user cannot log out from his/her account. The dialog box appears only for a second and can not be clicked. Same with the admin account when on the about us page

**Comment by KabirGc** [comment]
this bug has been fixed

![Screenshot 2021-05-15 103557](https://user-images.githubusercontent.com/82155584/118348963-683fb380-b56d-11eb-8ee9-5407cdeb54b5.png)
