### ISSUE TITLE
Log out 

### ISSUE THREAD

**Issue by KabirGc** [sumanbudhathoki9808/E-Challan#2]
If we try to log out of home page, the drop down menu is not stable. so we cannot log out if we enter the home page.

**Comment by sumanbudhathoki9808** [comment]
Decreasing the top margin for the dropdown menu might fix the problem.

**Comment by RabiKKC** [comment]
Okay, Kabir. I will look into the problem.

**Comment by RabiKKC** [comment]
This problem has been solved.
![Screenshot (423)](https://user-images.githubusercontent.com/81245282/114352576-c0108680-9b8b-11eb-8a00-6017029872db.png)
