### ISSUE TITLE
can not sign in to home page when click on sign 

### ISSUE THREAD

**Issue by biwaskerung999** [sumanbudhathoki9808/E-Challan#4]
![Screenshot (305)](https://user-images.githubusercontent.com/81351933/114640717-65446f80-9cf0-11eb-8a6e-d8503eba0eeb.png)

**Comment by biwaskerung999** [comment]
please check on the views loginpage function and html and url path connection for helping me in this issue

**Comment by KabirGc** [comment]
biwas check if the code is link to html file if not try using this code 
<a href= ***
"{% url 'home or index' %}" 
class="active-page">
Sign In
</a>
copy the code and paste it on login.html and dont add ***

**Comment by KabirGc** [comment]
''<a href="{% url 'home' %}" class="active-page">Home</a>''
