### ISSUE TITLE
Information 

### ISSUE THREAD

**Issue by dandaniels-dj** [sumanbudhathoki9808/E-Challan#8]
On the homepage, we can see information is shown with moving digit. The data provided on the homepage is around 6 years old i.e. 2015.  6 years span is long and data from it is totally useless. Imagine reading a 5 years old rule and implementing it now. It's the same i.e. useless. It does not make a huge difference but the data year should be changed as it provides information.

**Comment by biwaskerung999** [comment]
The data  are there to make aware to follow rules by showing the  numbers of accident in the past.

**Comment by sumanbudhathoki9808** [comment]
It's just a slider, we used it to show that the record is increasing. This website is not for general people. It is only for traffics.  The local user can get information from the website of traffic police which is made available to all the general public.
